name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        GOOS: [linux]
        GOARCH: [amd64, arm, arm64]
        GOARM: [7]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Download dependencies
        run: GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} go get -t -d ./...
      - name: Build source code for all architectures
        run: GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} go build
      - uses: actions/upload-artifact@v2
        with:
          name: geth-exporter-1.0.0-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: gethexporter
